#Lesson 4.7

In [1]:
#importing libraries
import pandas as pd
import numpy as np
import os

In [3]:
#define function
def add_num(x,y):
    sum = x + y
    return sum

In [4]:
#run function
add_num(9,11)

20

In [5]:
#importing data
path = r'C:\Users\alexa\OneDrive\Documents\data analytics\Achievement 4\01-09-2022 Instacart Basket Analysis'
df_ords_prods_merged=pd.read_pickle(os.path.join(path, '02 Data', 'Prepared Data', 'orders_products_merged.pkl'))

In [7]:
#limiting data legment to 1,000,000
df = df_ords_prods_merged[:1000000]

In [13]:
df.shape

(1000000, 17)

In [8]:
df.head()

,order_id,user_id,eval_set,order_number,Order_day_of_week,order_hour_of_day,Days since last order,New customer,product_id,add_to_cart_order,reordered,product_name,aisle_id,department_id,prices,_merge
0,2539329,1,prior,1,2,8,NaN,True,196.0,1.0,0.0,Soda,77,7,9.0,both
1,2398795,1,prior,2,3,7,15.0,False,196.0,1.0,1.0,Soda,77,7,9.0,both
2,473747,1,prior,3,3,12,21.0,False,196.0,1.0,1.0,Soda,77,7,9.0,both
3,2254736,1,prior,4,4,7,29.0,False,196.0,1.0,1.0,Soda,77,7,9.0,both
4,431534,1,prior,5,4,15,28.0,False,196.0,1.0,1.0,Soda,77,7,9.0,both

In [11]:
#using if to define price ranges
def price_label(row):
    if row['prices'] <=5:
        return 'Low-range products'
    elif (row['prices'] >5) and (row['prices'] <=15):
        return 'Mid-range products'
    elif row['prices'] >15:
        return 'High range products'
    else: return 'Not enough data'

In [12]:
df['price_range'] = df.apply(price_label, axis=1)

C:\Users\alexa\AppData\Local\Temp\ipykernel_10340\2848743372.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['price_range'] = df.apply(price_label, axis=1)

In [14]:
df['price_range'].value_counts(dropna = False)

Mid-range products    756450
Low-range products    243550
Name: price_range, dtype: int64

In [15]:
df['prices'].max()

14.8

In [23]:
#using loc to define price segments
df.loc[df['prices'] >15, 'price_range_loc'] = 'High-range products'

In [22]:
df.loc[(df['prices'] <=15) & (df['prices'] >5), 'price_range_loc'] = 'Mid range products'

In [21]:
df.loc[df['prices'] <= 5, 'price_range_loc'] = 'Low range products'

In [24]:
df['price_range_loc'].value_counts(dropna = False)

Mid range products    756450
Low range products    243550
Name: price_range_loc, dtype: int64

In [25]:
#using loc to main dataframe
df_ords_prods_merged.loc[df_ords_prods_merged['prices'] >15, 'price_range_loc'] = 'High-range products'

In [26]:
df_ords_prods_merged.loc[(df_ords_prods_merged['prices'] <=15) & (df['prices'] >5), 'price_range_loc'] = 'Mid range products'

In [27]:
df_ords_prods_merged.loc[df_ords_prods_merged['prices'] <= 5, 'price_range_loc'] = 'Low range products'

In [28]:
df_ords_prods_merged['price_range_loc'].value_counts(dropna = False)

NaN                    21104410
Low range products     10126321
Mid range products       756450
High-range products      417678
Name: price_range_loc, dtype: int64

In [30]:
df_ords_prods_merged.head()

,order_id,user_id,eval_set,order_number,Order_day_of_week,order_hour_of_day,Days since last order,New customer,product_id,add_to_cart_order,reordered,product_name,aisle_id,department_id,prices,_merge,price_range_loc
0,2539329,1,prior,1,2,8,NaN,True,196.0,1.0,0.0,Soda,77,7,9.0,both,Mid range products
1,2398795,1,prior,2,3,7,15.0,False,196.0,1.0,1.0,Soda,77,7,9.0,both,Mid range products
2,473747,1,prior,3,3,12,21.0,False,196.0,1.0,1.0,Soda,77,7,9.0,both,Mid range products
3,2254736,1,prior,4,4,7,29.0,False,196.0,1.0,1.0,Soda,77,7,9.0,both,Mid range products
4,431534,1,prior,5,4,15,28.0,False,196.0,1.0,1.0,Soda,77,7,9.0,both,Mid range products

In [33]:
#what are the busiest days
df_ords_prods_merged['Order_day_of_week'].value_counts(dropna = False)

0    6204182
1    5660230
6    4496490
2    4213830
5    4205791
3    3840534
4    3783802
Name: Order_day_of_week, dtype: int64

In [40]:
#creating a loop
result = []

for value in df_ords_prods_merged['Order_day_of_week']:
    if value == 0:
        result.append('Busiest day')
    elif value == 4:
            result.append('Least busy')
    else:
                result.append('Regular busy')

In [41]:
result

['Regular busy',
 'Regular busy',
 'Regular busy',
 'Least busy',
 'Least busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Least busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Least busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Least busy',
 'Least busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Least busy',
 'Regular busy',
 'Busiest day',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Busiest day',
 'Least busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Busiest day',
 'Regular busy',
 'Regular busy',
 'Least busy',
 'Regular busy',
 'Least busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Least busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Least busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Least busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Busiest day',
 'Regular busy',
 'Busiest day',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Busiest day',
 'Regular busy',
 'Least busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Least busy',
 'Regular busy',
 'Regular busy',
 'Busiest day',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Busiest day',
 'Regular busy',
 'Regular busy',
 'Least busy',
 'Least busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Busiest day',
 'Regular busy',
 'Busiest day',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Least busy',
 'Regular busy',
 'Regular busy',
 'Busiest day',
 'Busiest day',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Busiest day',
 'Regular busy',
 'Regular busy',
 'Least busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Least busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Least busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Least busy',
 'Regular busy',
 'Regular busy',
 'Busiest day',
 'Regular busy',
 'Least busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Busiest day',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Least busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Least busy',
 'Least busy',
 'Least busy',
 'Regular busy',
 'Regular busy',
 'Least busy',
 'Regular busy',
 'Least busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Busiest day',
 'Busiest day',
 'Busiest day',
 'Busiest day',
 'Busiest day',
 'Busiest day',
 'Regular busy',
 'Least busy',
 'Busiest day',
 'Regular busy',
 'Regular busy',
 'Least busy',
 'Regular busy',
 'Regular busy',
 'Least busy',
 'Least busy',
 'Regular busy',
 'Busiest day',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Busiest day',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Least busy',
 'Regular busy',
 'Least busy',
 'Regular busy',
 'Regular busy',
 'Least busy',
 'Busiest day',
 'Busiest day',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Busiest day',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Least busy',
 'Least busy',
 'Least busy',
 'Regular busy',
 'Regular busy',
 'Least busy',
 'Regular busy',
 'Least busy',
 'Busiest day',
 'Regular busy',
 'Busiest day',
 'Busiest day',
 'Regular busy',
 'Busiest day',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Least busy',
 'Regular busy',
 'Least busy',
 'Regular busy',
 'Regular busy',
 'Least busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Busiest day',
 'Regular busy',
 'Regular busy',
 'Busiest day',
 'Regular busy',
 'Regular busy',
 'Busiest day',
 'Regular busy',
 'Least busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Busiest day',
 'Regular busy',
 'Least busy',
 'Regular busy',
 'Busiest day',
 'Regular busy',
 'Least busy',
 'Regular busy',
 'Least busy',
 'Regular busy',
 'Regular busy',
 'Least busy',
 'Regular busy',
 'Regular busy',
 'Least busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Busiest day',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Busiest day',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Busiest day',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Least busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Least busy',
 'Regular busy',
 'Regular busy',
 'Least busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Least busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Least busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Least busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Least busy',
 'Regular busy',
 'Least busy',
 'Least busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Busiest day',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Busiest day',
 'Busiest day',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Least busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Least busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Least busy',
 'Least busy',
 'Least busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Busiest day',
 'Regular busy',
 'Regular busy',
 'Least busy',
 'Regular busy',
 'Regular busy',
 'Busiest day',
 'Least busy',
 'Busiest day',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Least busy',
 'Regular busy',
 'Regular busy',
 'Busiest day',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Busiest day',
 'Least busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Least busy',
 'Least busy',
 'Regular busy',
 'Least busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Least busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Least busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Least busy',
 'Regular busy',
 'Regular busy',
 'Least busy',
 'Least busy',
 'Regular busy',
 'Busiest day',
 'Busiest day',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Least busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Least busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Least busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Least busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Busiest day',
 'Busiest day',
 'Regular busy',
 'Regular busy',
 'Busiest day',
 'Regular busy',
 'Busiest day',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Busiest day',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Busiest day',
 'Regular busy',
 'Least busy',
 'Least busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Least busy',
 'Regular busy',
 'Least busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Busiest day',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Least busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Busiest day',
 'Regular busy',
 'Regular busy',
 'Least busy',
 'Regular busy',
 'Regular busy',
 'Least busy',
 'Least busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Least busy',
 'Regular busy',
 'Least busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Busiest day',
 'Regular busy',
 'Least busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Least busy',
 'Regular busy',
 'Regular busy',
 'Busiest day',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Least busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Least busy',
 'Regular busy',
 'Least busy',
 'Least busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Least busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Least busy',
 'Busiest day',
 'Regular busy',
 'Regular busy',
 'Least busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Busiest day',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Least busy',
 'Regular busy',
 'Regular busy',
 'Busiest day',
 'Regular busy',
 'Busiest day',
 'Regular busy',
 'Least busy',
 'Regular busy',
 'Regular busy',
 'Least busy',
 'Least busy',
 'Regular busy',
 'Regular busy',
 'Least busy',
 'Least busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Least busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Least busy',
 'Regular busy',
 'Least busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Least busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Least busy',
 'Regular busy',
 'Least busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Least busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Least busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Least busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Busiest day',
 'Regular busy',
 'Least busy',
 'Least busy',
 'Least busy',
 'Regular busy',
 'Busiest day',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Least busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Least busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Least busy',
 'Regular busy',
 'Regular busy',
 'Least busy',
 'Busiest day',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Least busy',
 'Least busy',
 'Least busy',
 'Least busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Least busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Busiest day',
 'Least busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Least busy',
 'Regular busy',
 'Regular busy',
 'Busiest day',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Least busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Least busy',
 'Regular busy',
 'Regular busy',
 'Least busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Least busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Least busy',
 'Least busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Least busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Busiest day',
 'Busiest day',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 ...]

In [42]:
df_ords_prods_merged['Busiest day'] = result

In [44]:
df_ords_prods_merged['Busiest day'].value_counts(dropna = False)

Regular busy    22416875
Busiest day      6204182
Least busy       3783802
Name: Busiest day, dtype: int64

In [45]:
df_ords_prods_merged.head()

,order_id,user_id,eval_set,order_number,Order_day_of_week,order_hour_of_day,Days since last order,New customer,product_id,add_to_cart_order,reordered,product_name,aisle_id,department_id,prices,_merge,price_range_loc,Busiest day
0,2539329,1,prior,1,2,8,NaN,True,196.0,1.0,0.0,Soda,77,7,9.0,both,Mid range products,Regular busy
1,2398795,1,prior,2,3,7,15.0,False,196.0,1.0,1.0,Soda,77,7,9.0,both,Mid range products,Regular busy
2,473747,1,prior,3,3,12,21.0,False,196.0,1.0,1.0,Soda,77,7,9.0,both,Mid range products,Regular busy
3,2254736,1,prior,4,4,7,29.0,False,196.0,1.0,1.0,Soda,77,7,9.0,both,Mid range products,Least busy
4,431534,1,prior,5,4,15,28.0,False,196.0,1.0,1.0,Soda,77,7,9.0,both,Mid range products,Least busy

# Task4.7

In [77]:
#2 question: changing loop to add extra column for 2 busiest days and 2 slowest days
result = []

for value in df_ords_prods_merged['Order_day_of_week']:
    if value == 0:
        result.append('Two busiest days')
    elif value == 1:
        result.append('Two busiest days')
    elif value == 3:
        result.append('Two slowest days')
    elif value ==4:
        result.append('Two slowest days')
    else:
        result.append('Regular busy')

In [78]:
df_ords_prods_merged['2 busy/slow days'] = result

In [79]:
#3 question: check format
df_ords_prods_merged['2 busy/slow days'].value_counts(dropna = False)

Regular busy        12916111
Two busiest days    11864412
Two slowest days     7624336
Name: 2 busy/slow days, dtype: int64

In [80]:
df_ords_prods_merged.head()

,order_id,user_id,eval_set,order_number,Order_day_of_week,order_hour_of_day,Days since last order,New customer,product_id,add_to_cart_order,reordered,product_name,aisle_id,department_id,prices,_merge,price_range_loc,Busiest day,2 busy/slow days
0,2539329,1,prior,1,2,8,NaN,True,196.0,1.0,0.0,Soda,77,7,9.0,both,Mid range products,Regular busy,Regular busy
1,2398795,1,prior,2,3,7,15.0,False,196.0,1.0,1.0,Soda,77,7,9.0,both,Mid range products,Regular busy,Two slowest days
2,473747,1,prior,3,3,12,21.0,False,196.0,1.0,1.0,Soda,77,7,9.0,both,Mid range products,Regular busy,Two slowest days
3,2254736,1,prior,4,4,7,29.0,False,196.0,1.0,1.0,Soda,77,7,9.0,both,Mid range products,Least busy,Two slowest days
4,431534,1,prior,5,4,15,28.0,False,196.0,1.0,1.0,Soda,77,7,9.0,both,Mid range products,Least busy,Two slowest days

In [81]:
#4 question: what are the times of the days
df_ords_prods_merged['order_hour_of_day'].value_counts(dropna = False)

10    2761760
11    2736140
14    2689136
15    2662144
13    2660954
12    2618532
16    2535202
9     2454203
17    2087654
8     1718118
18    1636502
19    1258305
20     976156
7      891054
21     795637
22     634225
23     402316
6      290493
0      218769
1      115700
5       87961
2       69375
4       53242
3       51281
Name: order_hour_of_day, dtype: int64

will devide them into these buckets:
- most orders: hours 10,11,14,15,13,12,16,9,17 (9,17)
- average orders:  hours 8,18,19,20,7,21,22,23,6,0,1 (0,1)(18,23)(6,7,8)
- fewest orders:  5,2,4,3 (3,5)

In [110]:
result = []

for value in df_ords_prods_merged['order_hour_of_day']:
    if value in range (9,17):
        result.append('Most orders')
    elif value in range(3,5):
        result.append('Fewest orders')
    else:
        result.append('Average orders')

In [111]:
df_ords_prods_merged['busiest_period_of_day'] = result

In [112]:
#5 question: check format
df_ords_prods_merged['busiest_period_of_day'].value_counts(dropna = False)

Most orders       21118071
Average orders    11182265
Fewest orders       104523
Name: busiest_period_of_day, dtype: int64

In [113]:
df_ords_prods_merged.to_pickle(os.path.join(path, '02 Data','Prepared Data', 'order_busy_frequencies.pkl'))